export const skills = [
    "Angular",
    "TypeScript",
    "JavaScript",
    "NestJS",
    "Node.js",
    "MongoDB",
    "PostgreSQL",
    "Docker",
    "Microservices",
    "REST API",
    "TailwindCSS",
    "SCSS",
    "Git",
    "CI/CD",
    "GSAP",
];